#pragma once

#define FOOTER_HEIGHT 1
#define DATE_LIST_WIDTH 30

#define STD_COLOR_PAIR 1
#define FOOTER_COLOR_PAIR 99
#define HIGHLIGHT_EXPR_COLOR_PAR 98

#define A_HIGHLIGHT (A_STANDOUT | COLOR_PAIR(HIGHLIGHT_EXPR_COLOR_PAR))

#define KEY_ARROW_UP KEY_UP
#define KEY_ARROW_DOWN KEY_DOWN
